# Site settings
title: Style Changer
email: swashcap@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Experimental style changer with AngularJS.
baseurl: "/style-changer/" # the subpath of your site, e.g. /blog/
url: "http://swashcap.github.io" # the base hostname & protocol for your site
twitter_username: swashcap
github_username:  swashcap

# Build settings
markdown: kramdown
